<?php
require_once "./includes/header.php";

$vehicle_id = isset($_GET['vehicleId']) ? intval($_GET['vehicleId']) : 1;

// Fetch vehicle details
$vehicle_query = "SELECT * FROM routes 
                  JOIN vehicle_lists ON routes.id = vehicle_lists.route_id 
                  WHERE vehicle_lists.id = ?";
$stmt = mysqli_prepare($conn, $vehicle_query);
mysqli_stmt_bind_param($stmt, "i", $vehicle_id);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);
$vehicle_list = mysqli_fetch_all($result, MYSQLI_ASSOC);

// Fetch routing dates
$route_query = "SELECT * FROM route_date WHERE vehicle_id = ?";
$stmt2 = mysqli_prepare($conn, $route_query);
mysqli_stmt_bind_param($stmt2, "i", $vehicle_id);
mysqli_stmt_execute($stmt2);
$route_result = mysqli_stmt_get_result($stmt2);
$route_dates = mysqli_fetch_all($route_result, MYSQLI_ASSOC);

// Fetch occupied seats
$occupiedSeats = [];
$sql = "SELECT seat_number FROM booking_seats 
        JOIN bookings ON booking_seats.booking_id = bookings.id 
        WHERE bookings.vehicle_id = ?";
$stmt3 = $conn->prepare($sql);
$stmt3->bind_param("i", $vehicle_id);
$stmt3->execute();
$result3 = $stmt3->get_result();
while ($row = $result3->fetch_assoc()) {
    $occupiedSeats[] = intval($row['seat_number']);
}

// Encode occupied seats for JS
$occupiedSeatsJson = json_encode($occupiedSeats);
?>

<section id="booking-section">
    <div class="container">
        <div class="booking-container">
            <?php if(!empty($vehicle_list)): ?>
                <?php $vehicle = $vehicle_list[0]; ?>
                <div class="bus-detail">
                    <div class="booking-poster">
                        <img src="./assets/images/Bus.png" alt="">
                    </div>
                    <div class="booking-details">
                        <h2 class="booking-title"><?= htmlspecialchars($vehicle['startin']) ?> To <?= htmlspecialchars($vehicle['destination']) ?></h2>
                        <div class="booking-info">
                            <p><strong>Boarding Time: </strong><?= htmlspecialchars($vehicle['starttime']) ?></p>
                            <p><strong>Dropping Time: </strong><?= htmlspecialchars($vehicle['endtime']) ?></p>
                            <p><strong>Facilities: </strong><?= htmlspecialchars($vehicle['facilities']) ?></p>
                            <p><strong>Total Seats: </strong><?= $vehicle['total_seats'] ?: 33 ?></p>
                            <p><strong>Available Seats: </strong><span id="available-seats"><?= ($vehicle['total_seats'] ?: 33) - count($occupiedSeats) ?></span></p>
                            <p><strong>Bus Number: </strong><?= htmlspecialchars($vehicle['vehicle_number']) ?></p>
                            <p><strong>Driver Name: </strong><?= htmlspecialchars($vehicle['driver_name']) ?></p>
                            <p><strong>Driver Phone Number: </strong><?= htmlspecialchars($vehicle['driver_phone_number']) ?></p>
                        </div>
                    </div>
                </div>

                <form action="./process_booking.php" method="POST" id="booking-form">
                    <input type="hidden" name="vehicle_id" value="<?= $vehicle_id ?>">
                    <input type="hidden" name="selected_seats" id="selected-seats" value="">
                    <input type="hidden" name="total_price" id="total-price" value="0">

                    <div class="form-group">
                        <label for="" style="color:black;">Select Date</label>
                        <select name="route_date_id" required>
                            <?php foreach($route_dates as $routedate): ?>
                                <option value="<?= $routedate['id'] ?>"><?= date('d/m/Y', strtotime($routedate['routing_date'])) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="seat-details">
                        <h3>Select Your Seat</h3>
                        <div class="front">Front of Bus</div>
                        <div class="bus" id="bus">
                            <!-- Seats generated by JS -->
                        </div> 
                    </div>

                    <div class="form-group total-price">
                        <strong>Total Price: </strong><span>Rs. 0</span>
                    </div>

                    <button type="submit" id="pay-button" class="confirm-btn">Confirm Booking</button>
                </form>
            <?php else: ?>
                <p>No vehicle details found.</p>
            <?php endif; ?>
        </div>
    </div>
</section>


<script>

document.getElementById('booking-form').addEventListener('submit', function (e) {
    if (selectedSeats.length === 0) {
        alert("Please select at least one seat!");
        e.preventDefault(); // stop form submission
    }
});


const busTicketPrice = <?= $vehicle['price'] ?>;
const totalSeats = <?= $vehicle['total_seats'] ?: 33 ?>;
const occupiedSeats = <?= $occupiedSeatsJson ?>;
const bus = document.getElementById('bus');
let selectedSeats = [];

const selectedSeatsInput = document.getElementById('selected-seats');
const totalPriceInput = document.getElementById('total-price');
const availableSeatsDisplay = document.getElementById('available-seats');

// Generate seats dynamically
for (let i = 1; i <= totalSeats; i++) {
    const seat = document.createElement('div');
    seat.classList.add('seat');
    seat.innerHTML = `<i class="fas fa-chair"></i>`;
    seat.title = `Seat ${i}`;

    if (occupiedSeats.includes(i)) {
        seat.classList.add('occupied');
    }

    seat.addEventListener('click', () => {
        if (!seat.classList.contains('occupied')) {
            seat.classList.toggle('selected');
            if (seat.classList.contains('selected')) {
                selectedSeats.push(i);
            } else {
                selectedSeats = selectedSeats.filter(s => s !== i);
            }
            updateBookingSummary();
        }
    });

    bus.appendChild(seat);
}

function updateBookingSummary() {
    selectedSeatsInput.value = selectedSeats.join(",");
    totalPriceInput.value = selectedSeats.length * busTicketPrice;

    // Update available seats
    const availableSeats = totalSeats - occupiedSeats.length - selectedSeats.length;
    if (availableSeatsDisplay) {
        availableSeatsDisplay.textContent = availableSeats;
    }

    // Update total price display
    const totalDisplay = document.querySelector('.total-price span');
    if (totalDisplay) {
        totalDisplay.textContent = "Rs. " + (selectedSeats.length * busTicketPrice);
    }

    

}
</script>

<?php
require_once "./includes/footer.php";
?>
